import candle from "@/assets/product-candle.jpg";
import chocolate from "@/assets/product-chocolate.jpg";
import kurti from "@/assets/product-kurti.jpg";
import plant from "@/assets/product-plant.jpg";
import jewellery from "@/assets/product-jewellery.jpg";
import giftbox from "@/assets/product-giftbox.jpg";

import type {
  Notification,
  Order,
  Product,
  RegistrationPayment,
  Report,
  Review,
  Seller,
  User,
} from "./types";

export const IMAGES: Record<string, string> = {
  candle,
  chocolate,
  kurti,
  plant,
  jewellery,
  giftbox,
};

export const REGISTRATION_FEE = 99;

export const demoUsers: User[] = [
  {
    id: "u-seller-1",
    role: "SELLER",
    fullName: "Rutuja Kolate",
    email: "rutuja@homehub.in",
    mobile: "98200 11223",
    password: "seller123",
    createdAt: "2025-11-04",
  },
  {
    id: "u-seller-2",
    role: "SELLER",
    fullName: "Anita Deshpande",
    email: "anita@homehub.in",
    mobile: "98200 44556",
    password: "seller123",
    createdAt: "2025-12-12",
  },
  {
    id: "u-seller-3",
    role: "SELLER",
    fullName: "Meera Iyer",
    email: "meera@homehub.in",
    mobile: "98200 77889",
    password: "seller123",
    createdAt: "2026-01-20",
  },
  {
    id: "u-seller-4",
    role: "SELLER",
    fullName: "Sahil Rane",
    email: "sahil@homehub.in",
    mobile: "98200 99001",
    password: "seller123",
    createdAt: "2026-03-02",
  },
  {
    id: "u-seller-5",
    role: "SELLER",
    fullName: "Farah Sheikh",
    email: "farah@homehub.in",
    mobile: "98200 22334",
    password: "seller123",
    createdAt: "2026-07-18",
  },
  {
    id: "u-buyer-1",
    role: "BUYER",
    fullName: "Nikhil Sharma",
    email: "buyer@homehub.in",
    mobile: "98111 23456",
    password: "buyer123",
    createdAt: "2026-02-10",
  },
  {
    id: "u-buyer-2",
    role: "BUYER",
    fullName: "Priya Nair",
    email: "priya@homehub.in",
    mobile: "98111 65432",
    password: "buyer123",
    createdAt: "2026-04-22",
  },
  {
    id: "u-admin-1",
    role: "ADMIN",
    fullName: "HomeHub Admin",
    email: "admin@homehub.in",
    mobile: "98000 00000",
    password: "admin123",
    createdAt: "2025-10-01",
  },
];

export const demoSellers: Seller[] = [
  {
    id: "s-1",
    userId: "u-seller-1",
    storeName: "Rutuja Handmade Crafts",
    businessType: "Home-based business",
    businessCategory: "Handmade products",
    location: "Pune, Maharashtra",
    description:
      "Hand-poured soy candles, gift hampers and small home decor pieces, made at home in small batches.",
    yearsInBusiness: "3 years",
    productCategory: "Handmade products",
    productCount: "10-25",
    instagram: "https://instagram.com/rutuja.handmade",
    whatsapp: "98200 11223",
    otherLinks: "",
    status: "ACTIVE",
    verified: true,
    rating: 4.8,
    joinedAt: "2025-11-04",
    sells: ["Handmade products", "Home decor"],
    sellsNow: ["WhatsApp", "Instagram"],
    wantsToSell: "Across India",
    guidanceDone: ["basic", "udyam"],
  },
  {
    id: "s-2",
    userId: "u-seller-2",
    storeName: "Pune Home Bakery",
    businessType: "Home kitchen",
    businessCategory: "Food",
    location: "Pune, Maharashtra",
    description:
      "Small home bakery making eggless cakes, cookie boxes and handmade chocolates to order.",
    yearsInBusiness: "5 years",
    productCategory: "Food",
    productCount: "5-10",
    instagram: "https://instagram.com/punehomebakery",
    whatsapp: "98200 44556",
    otherLinks: "",
    status: "ACTIVE",
    verified: true,
    rating: 4.9,
    joinedAt: "2025-12-12",
    sells: ["Food"],
    sellsNow: ["WhatsApp", "Local store"],
    wantsToSell: "Within state",
    guidanceDone: ["basic"],
  },
  {
    id: "s-3",
    userId: "u-seller-3",
    storeName: "Local Threads Boutique",
    businessType: "Small shop",
    businessCategory: "Clothing",
    location: "Nashik, Maharashtra",
    description:
      "Block-printed cotton kurtis and everyday wear sourced from local weavers and tailored in-house.",
    yearsInBusiness: "2 years",
    productCategory: "Clothing",
    productCount: "25-50",
    instagram: "https://instagram.com/localthreads",
    whatsapp: "98200 77889",
    otherLinks: "",
    status: "ACTIVE",
    verified: false,
    rating: 4.6,
    joinedAt: "2026-01-20",
    sells: ["Clothing"],
    sellsNow: ["Instagram", "Local store"],
    wantsToSell: "Across India",
    guidanceDone: ["basic"],
  },
  {
    id: "s-4",
    userId: "u-seller-4",
    storeName: "EcoPlant Studio",
    businessType: "Home-based business",
    businessCategory: "Plants",
    location: "Bengaluru, Karnataka",
    description: "Indoor plants in hand-painted terracotta pots, grown and packed at home.",
    yearsInBusiness: "1 year",
    productCategory: "Plants",
    productCount: "10-25",
    instagram: "https://instagram.com/ecoplant.studio",
    whatsapp: "98200 99001",
    otherLinks: "",
    status: "ACTIVE",
    verified: true,
    rating: 4.7,
    joinedAt: "2026-03-02",
    sells: ["Plants", "Home decor"],
    sellsNow: ["WhatsApp"],
    wantsToSell: "Local area",
    guidanceDone: ["basic"],
  },
  {
    id: "s-5",
    userId: "u-seller-5",
    storeName: "Handmade Gift Corner",
    businessType: "Home-based business",
    businessCategory: "Handmade products",
    location: "Hyderabad, Telangana",
    description: "Custom gift hampers and handmade jewellery for weddings and festivals.",
    yearsInBusiness: "Less than 1 year",
    productCategory: "Jewellery",
    productCount: "1-5",
    instagram: "https://instagram.com/handmadegiftcorner",
    whatsapp: "98200 22334",
    otherLinks: "",
    status: "PENDING",
    verified: false,
    rating: 0,
    joinedAt: "2026-07-18",
    sells: ["Jewellery", "Handmade products"],
    sellsNow: ["Instagram", "Facebook"],
    wantsToSell: "Within state",
    guidanceDone: [],
  },
];

export const demoProducts: Product[] = [
  {
    id: "p-1",
    sellerId: "s-1",
    name: "Handmade Lavender Candle",
    description:
      "Hand-poured soy wax candle with natural lavender essential oil in a reusable ceramic jar. Burns for about 35 hours.",
    category: "Home decor",
    price: 449,
    mrp: 549,
    stock: 24,
    size: "200 g jar",
    colour: "Off-white",
    variants: "Lavender, Rose, Vanilla",
    weight: "320 g",
    delivery: "Ships in 2-3 days across India",
    availability: "Available",
    image: "candle",
    status: "ACTIVE",
    views: 1284,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2025-11-10",
    tags: ["candle", "soy wax", "handmade", "gift"],
  },
  {
    id: "p-2",
    sellerId: "s-1",
    name: "Handmade Gift Hamper Box",
    description:
      "A curated hamper with a soy candle, handmade soap and dried flowers, wrapped in recycled paper.",
    category: "Handmade products",
    price: 899,
    stock: 12,
    size: "Medium box",
    colour: "Kraft brown",
    variants: "Small, Medium",
    weight: "900 g",
    delivery: "Ships in 3-4 days",
    availability: "Available",
    image: "giftbox",
    status: "ACTIVE",
    views: 742,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2025-12-02",
    tags: ["gift", "hamper", "handmade"],
  },
  {
    id: "p-3",
    sellerId: "s-2",
    name: "Handmade Chocolate Box",
    description:
      "Nine assorted handmade chocolates — dark, milk and white — packed fresh in a gift box.",
    category: "Food",
    price: 320,
    mrp: 380,
    stock: 40,
    size: "9 pieces",
    colour: "-",
    variants: "9 pieces, 16 pieces",
    weight: "250 g",
    delivery: "Local delivery in Pune, 1-2 days",
    availability: "Available",
    image: "chocolate",
    status: "ACTIVE",
    views: 2140,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2025-12-18",
    tags: ["chocolate", "homemade", "gift"],
  },
  {
    id: "p-4",
    sellerId: "s-3",
    name: "Block Print Cotton Kurti",
    description:
      "Indigo block-printed cotton kurti, breathable and stitched in-house. Available in sizes S to XXL.",
    category: "Clothing",
    price: 1299,
    mrp: 1599,
    stock: 18,
    size: "S, M, L, XL, XXL",
    colour: "Indigo",
    variants: "Indigo, Maroon",
    weight: "350 g",
    delivery: "Ships in 3-5 days across India",
    availability: "Available",
    image: "kurti",
    status: "ACTIVE",
    views: 1876,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-02-01",
    tags: ["kurti", "cotton", "block print"],
  },
  {
    id: "p-5",
    sellerId: "s-4",
    name: "Decorative Money Plant",
    description:
      "Money plant in a hand-painted terracotta pot with drainage tray. Easy to care for, indoor friendly.",
    category: "Plants",
    price: 599,
    stock: 9,
    size: "6 inch pot",
    colour: "Terracotta",
    variants: "6 inch, 8 inch",
    weight: "1.2 kg",
    delivery: "Ships in 2-4 days, packed with care",
    availability: "Available",
    image: "plant",
    status: "ACTIVE",
    views: 964,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-03-14",
    tags: ["plant", "indoor", "terracotta"],
  },
  {
    id: "p-6",
    sellerId: "s-5",
    name: "Handmade Oxidised Jewellery Set",
    description:
      "Oxidised silver-tone necklace with matching jhumkas, strung by hand on black thread.",
    category: "Jewellery",
    price: 749,
    mrp: 899,
    stock: 6,
    size: "Adjustable",
    colour: "Oxidised silver",
    variants: "Necklace only, Full set",
    weight: "120 g",
    delivery: "Ships in 4-5 days",
    availability: "Available",
    image: "jewellery",
    status: "PENDING_REVIEW",
    views: 0,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-09-16",
    tags: ["jewellery", "oxidised", "handmade"],
  },
  {
    id: "p-7",
    sellerId: "s-1",
    name: "Rose Soy Candle (Travel Tin)",
    description: "Small travel-size rose soy candle in a metal tin. Burns for about 12 hours.",
    category: "Home decor",
    price: 249,
    stock: 0,
    size: "100 g tin",
    colour: "Blush",
    variants: "Rose, Jasmine",
    weight: "160 g",
    delivery: "Ships in 2-3 days",
    availability: "Out of stock",
    image: "candle",
    status: "OUT_OF_STOCK",
    views: 388,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-05-09",
    tags: ["candle", "travel", "small"],
  },
  {
    id: "p-8",
    sellerId: "s-2",
    name: "Festive Cookie Tin",
    description: "Butter cookies in four flavours, packed in a reusable festive tin.",
    category: "Food",
    price: 540,
    stock: 15,
    size: "500 g tin",
    colour: "-",
    variants: "500 g, 1 kg",
    weight: "600 g",
    delivery: "Local delivery in Pune",
    availability: "Available",
    image: "chocolate",
    status: "CHANGES_REQUIRED",
    views: 0,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-09-10",
    adminNote:
      "Please add clear ingredient and allergen information in the description, then resubmit.",
    tags: ["cookies", "festive"],
  },
  {
    id: "p-9",
    sellerId: "s-3",
    name: "Handloom Cotton Dupatta",
    description: "Lightweight handloom dupatta in natural dye, woven by local weavers.",
    category: "Clothing",
    price: 699,
    stock: 22,
    size: "2.25 m",
    colour: "Mustard",
    variants: "Mustard, Olive",
    weight: "200 g",
    delivery: "Ships in 3-5 days",
    availability: "Available",
    image: "kurti",
    status: "ACTIVE",
    views: 512,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-04-11",
    tags: ["dupatta", "handloom"],
  },
  {
    id: "p-10",
    sellerId: "s-4",
    name: "Desk Succulent Trio",
    description: "Three small succulents in mini painted pots — perfect for a desk or shelf.",
    category: "Plants",
    price: 449,
    stock: 11,
    size: "3 inch pots",
    colour: "Mixed",
    variants: "Trio, Pair",
    weight: "900 g",
    delivery: "Ships in 2-4 days",
    availability: "Available",
    image: "plant",
    status: "ACTIVE",
    views: 617,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-06-05",
    tags: ["succulent", "desk", "plant"],
  },
  {
    id: "p-11",
    sellerId: "s-5",
    name: "Wedding Favour Mini Hamper",
    description: "Mini hamper with a tea light, chocolate and thank-you card for wedding favours.",
    category: "Handmade products",
    price: 199,
    stock: 50,
    size: "Mini",
    colour: "Ivory",
    variants: "Pack of 10, Pack of 25",
    weight: "150 g",
    delivery: "Ships in 5-7 days",
    availability: "Available",
    image: "giftbox",
    status: "REJECTED",
    views: 0,
    registrationFee: REGISTRATION_FEE,
    registeredAt: "2026-09-12",
    adminNote:
      "Product photos did not show the actual hamper contents. Please upload your own photos and register again.",
    tags: ["favour", "wedding"],
  },
];

export const demoOrders: Order[] = [
  {
    id: "HH-2041",
    buyerId: "u-buyer-1",
    sellerId: "s-3",
    items: [
      {
        productId: "p-4",
        name: "Block Print Cotton Kurti",
        image: "kurti",
        price: 1299,
        quantity: 2,
        sellerId: "s-3",
      },
    ],
    amount: 2598,
    delivery: 0,
    status: "NEW",
    paymentMethod: "UPI",
    address: {
      fullName: "Nikhil Sharma",
      mobile: "98111 23456",
      line1: "Flat 402, Sunrise Residency, Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    placedAt: "2026-09-21",
  },
  {
    id: "HH-2038",
    buyerId: "u-buyer-1",
    sellerId: "s-1",
    items: [
      {
        productId: "p-1",
        name: "Handmade Lavender Candle",
        image: "candle",
        price: 449,
        quantity: 1,
        sellerId: "s-1",
      },
    ],
    amount: 449,
    delivery: 40,
    status: "SHIPPED",
    paymentMethod: "Card",
    address: {
      fullName: "Nikhil Sharma",
      mobile: "98111 23456",
      line1: "Flat 402, Sunrise Residency, Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    placedAt: "2026-09-16",
  },
  {
    id: "HH-2031",
    buyerId: "u-buyer-2",
    sellerId: "s-2",
    items: [
      {
        productId: "p-3",
        name: "Handmade Chocolate Box",
        image: "chocolate",
        price: 320,
        quantity: 3,
        sellerId: "s-2",
      },
    ],
    amount: 960,
    delivery: 0,
    status: "DELIVERED",
    paymentMethod: "Cash on Delivery",
    address: {
      fullName: "Priya Nair",
      mobile: "98111 65432",
      line1: "12, Green Meadows, Kothrud",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411038",
    },
    placedAt: "2026-09-05",
    reviewed: true,
  },
  {
    id: "HH-2024",
    buyerId: "u-buyer-1",
    sellerId: "s-1",
    items: [
      {
        productId: "p-2",
        name: "Handmade Gift Hamper Box",
        image: "giftbox",
        price: 899,
        quantity: 1,
        sellerId: "s-1",
      },
    ],
    amount: 899,
    delivery: 40,
    status: "DELIVERED",
    paymentMethod: "UPI",
    address: {
      fullName: "Nikhil Sharma",
      mobile: "98111 23456",
      line1: "Flat 402, Sunrise Residency, Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    placedAt: "2026-08-28",
  },
  {
    id: "HH-2019",
    buyerId: "u-buyer-2",
    sellerId: "s-4",
    items: [
      {
        productId: "p-5",
        name: "Decorative Money Plant",
        image: "plant",
        price: 599,
        quantity: 1,
        sellerId: "s-4",
      },
    ],
    amount: 599,
    delivery: 60,
    status: "PACKED",
    paymentMethod: "UPI",
    address: {
      fullName: "Priya Nair",
      mobile: "98111 65432",
      line1: "12, Green Meadows, Kothrud",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411038",
    },
    placedAt: "2026-09-19",
  },
  {
    id: "HH-2012",
    buyerId: "u-buyer-1",
    sellerId: "s-1",
    items: [
      {
        productId: "p-1",
        name: "Handmade Lavender Candle",
        image: "candle",
        price: 449,
        quantity: 4,
        sellerId: "s-1",
      },
    ],
    amount: 1796,
    delivery: 0,
    status: "CONFIRMED",
    paymentMethod: "Card",
    address: {
      fullName: "Nikhil Sharma",
      mobile: "98111 23456",
      line1: "Flat 402, Sunrise Residency, Baner",
      city: "Pune",
      state: "Maharashtra",
      pincode: "411045",
    },
    placedAt: "2026-09-20",
  },
];

export const demoPayments: RegistrationPayment[] = demoProducts
  .filter((p) => p.status !== "PENDING_PAYMENT")
  .map((p, i) => ({
    id: `pay-${i + 1}`,
    productId: p.id,
    sellerId: p.sellerId,
    amount: p.registrationFee,
    status: p.status === "REJECTED" ? "REFUNDED" : "SUCCESSFUL",
    paidAt: p.registeredAt,
    transactionId: `TXN${(920411 + i * 137).toString()}`,
  }));

export const demoReviews: Review[] = [
  {
    id: "r-1",
    productId: "p-1",
    sellerId: "s-1",
    buyerId: "u-buyer-2",
    buyerName: "Priya Nair",
    rating: 5,
    comment: "The candle smells wonderful and the jar is lovely. Packed really carefully.",
    createdAt: "2026-09-02",
  },
  {
    id: "r-2",
    productId: "p-1",
    sellerId: "s-1",
    buyerId: "u-buyer-1",
    buyerName: "Nikhil Sharma",
    rating: 4,
    comment: "Good quality, burns clean. Delivery took a day longer than expected.",
    createdAt: "2026-08-21",
  },
  {
    id: "r-3",
    productId: "p-3",
    sellerId: "s-2",
    buyerId: "u-buyer-2",
    buyerName: "Priya Nair",
    rating: 5,
    comment: "Chocolates were fresh and clearly handmade. Ordering again for Diwali.",
    createdAt: "2026-09-09",
  },
  {
    id: "r-4",
    productId: "p-4",
    sellerId: "s-3",
    buyerId: "u-buyer-1",
    buyerName: "Nikhil Sharma",
    rating: 4,
    comment: "Nice fabric and print. Sizing runs slightly small.",
    createdAt: "2026-07-30",
  },
  {
    id: "r-5",
    productId: "p-5",
    sellerId: "s-4",
    buyerId: "u-buyer-2",
    buyerName: "Priya Nair",
    rating: 5,
    comment: "Plant arrived healthy and the painted pot is gorgeous.",
    createdAt: "2026-08-14",
    reported: true,
  },
];

export const demoNotifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-seller-1",
    title: "Product approved",
    body: "Your product Handmade Lavender Candle has been approved and is live in your store.",
    tone: "success",
    createdAt: "2026-09-18",
    read: false,
  },
  {
    id: "n-2",
    userId: "u-seller-1",
    title: "New order received",
    body: "Order HH-2012 · 4 × Handmade Lavender Candle · ₹1,796",
    tone: "info",
    createdAt: "2026-09-20",
    read: false,
  },
  {
    id: "n-3",
    userId: "u-seller-1",
    title: "Low stock",
    body: "Rose Soy Candle (Travel Tin) is out of stock. Update stock to keep selling.",
    tone: "warning",
    createdAt: "2026-09-19",
    read: false,
  },
  {
    id: "n-4",
    userId: "u-seller-2",
    title: "Changes required",
    body: "Festive Cookie Tin needs ingredient details before it can be approved.",
    tone: "warning",
    createdAt: "2026-09-13",
    read: false,
  },
  {
    id: "n-5",
    userId: "u-buyer-1",
    title: "Order shipped",
    body: "Order HH-2038 has been shipped and should arrive in 2-3 days.",
    tone: "info",
    createdAt: "2026-09-18",
    read: false,
  },
  {
    id: "n-6",
    userId: "u-admin-1",
    title: "New product awaiting review",
    body: "Handmade Gift Corner submitted Handmade Oxidised Jewellery Set.",
    tone: "info",
    createdAt: "2026-09-16",
    read: false,
  },
  {
    id: "n-7",
    userId: "u-admin-1",
    title: "New seller registered",
    body: "Handmade Gift Corner (Hyderabad) is waiting for seller approval.",
    tone: "info",
    createdAt: "2026-07-18",
    read: false,
  },
];

export const demoReports: Report[] = [
  {
    id: "rep-1",
    raisedBy: "u-buyer-1",
    raisedByName: "Nikhil Sharma",
    role: "BUYER",
    type: "Product issue",
    subject: "Candle arrived cracked",
    details: "The jar had a crack on one side. The seller has offered a replacement.",
    status: "INVESTIGATING",
    createdAt: "2026-09-17",
  },
  {
    id: "rep-2",
    raisedBy: "u-buyer-2",
    raisedByName: "Priya Nair",
    role: "BUYER",
    type: "Misleading information",
    subject: "Pot size smaller than listed",
    details: "Listing said 6 inch pot, the pot received measures around 5 inch.",
    status: "OPEN",
    createdAt: "2026-09-20",
  },
  {
    id: "rep-3",
    raisedBy: "u-seller-2",
    raisedByName: "Anita Deshpande",
    role: "SELLER",
    type: "Buyer issue",
    subject: "Repeated cancellation after packing",
    details: "Same buyer cancelled three cash-on-delivery orders after they were packed.",
    status: "RESOLVED",
    resolution: "Buyer contacted and cash-on-delivery limited for this account.",
    createdAt: "2026-09-08",
  },
];
